#!/usr/bin/env bash
# Once MySQL replication is setup, add a new record in the
# table via MySQL on web-01 and check if the record has been
# replicated in MySQL web-02. If you see it, it means the
# replication is working!
[mysqld]
pid-file       = /var/run/mysqld/mysqld.pid
socket         = /var/run/mysqld/mysqld.sock
datadir        = /var/lib/mysql
log-error      = /var/log/mysql/error.log
symbolic-links = 0
server-id      = 1
log_bin        = /var/log/mysql/mysql-bin.log
binlog_do_db   = tyrell_corp
