#!/usr/bin/env bash
# A Bash script that configures the container to fit nginx run as nginx
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
pkill -9 apache
sudo -u nginx service nginx restart
